openapi: 3.0.0
info:
  version: "1.0"
  title: "SP Clothing"
schemes:
  - https

paths:
  /payment:
    $ref: "./paths/Payment.yaml"

definitions:
  Payment:
    $ref: "./definitions/Payment.yaml"
  PaymentResponse:
    $ref: "./definitions/PaymentResponse.yaml"
# securityDefinitions:
#   authorizer:
#     type: apiKey
#     name: Authorization
#     in: header
#     x-amazon-apigateway-authtype: cognito_user_pools
#     x-amazon-apigateway-authorizer:
#       type: cognito_user_pools
#       providerARNs:
#         - ${cognito_user_pool_arn}
