import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card/Card';
import styles from '../styles/Home.module.css';
import ContentfulApi from '../utils/ContentfulApi';

interface Props {
	products: any;
}

export interface ImageObject {
	title: string;
	description: string;
	url: string;
}

interface ProductData {
	description: string;
	name: string;
	imageCollection: imageCollectionData;
}

interface imageCollectionData {
	items: ImageObject[];
}

const Home: React.FC<Props> = ({ products }) => {
	console.log(products);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Products</h1>
				{products.map((product: any) => (
					<Card title={product.name} url="/" key={product.sys.id} img={product.imageCollection.items[0]} description={product.description} />
				))}
			</main>

			<footer className={styles.footer}>
				<a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;

export async function getStaticProps({ params: any, preview = false }) {
	const products = await ContentfulApi.getAllProducts();

	// Add this with fallback: "blocking"
	// So that if we do not have a post on production,
	// the 404 is served
	if (!products) {
		return {
			notFound: true
		};
	}
	return { props: { products } };
}
